### ISSUE TITLE
What actually is the default corner radius for libadwaita?

### ISSUE THREAD

**Issue by flexagoon** [yilozt/rounded-window-corners#49]
When border radius is set to less than 12, and "skip libadwaita applications" is turned off, there are those weird black borders around libadwaita apps.

![image](https://user-images.githubusercontent.com/66178592/188334024-126068d9-11fb-4c55-8b36-e510fe219047.png)

*Screenshot with border radius set to 0*

This seems to be caused by the fact that we're trying to make border radius of libadwaita apps smaller than the default libadwaita value, which is not possible. This by itself does not look like a bug. What's weird though is that the value at which this disappears is 12 and not 8, since the default libadwaita corner rounding is 8px as far as I can tell.

**Comment by flexagoon** [comment]
Wait, maybe I'm actually wrong! Looking at the code for mutter-rounded it seems that the default value is 12 there. https://github.com/yilozt/mutter-rounded/blob/0b444bf17323bae193fc6ce09ee8596ffff10e67/patches/rounded_corners.42.2.patch#L45

So if this is actually the default value in GNOME, #40 should be partially reverted, changing the default in this extension back to 12 as well.

**Comment by yilozt** [comment]
Border radius of libadwaita should be 12px:

```scss
/*
https://github.com/GNOME/libadwaita/blob/a578ebe7cb8727ca5158113704ecc63d65b4f7eb/src/stylesheet/widgets/_window.scss#L12
*/
window {
  &.csd {
    border-radius: $window_radius;
  }
}
```

```scss
/*
https://github.com/GNOME/libadwaita/blob/a578ebe7cb8727ca5158113704ecc63d65b4f7eb/src/stylesheet/_common.scss#L7-L12
*/
$button_radius: 6px;
$window_radius: $button_radius + 6;
```

This value can be confirmed when you check the CSS Nodes of a libadwaita window:

![image](https://user-images.githubusercontent.com/32430186/188356574-0396e826-5f36-4c15-b4be-c910fd461c92.png)
